name = "deepsite-main"
compatibility_date = "2024-01-01"

[env.production]
name = "deepsite-main"

# Custom domain configuration
[[env.production.routes]]
pattern = "9gent.com/*"
zone_name = "9gent.com"

# Build configuration - remove cache after build to avoid 25MB limit
[build]
command = "npm run build && rm -rf .next/cache cache"
cwd = "."
watch_dir = "."

# Pages configuration - use .next output
pages_build_output_dir = ".next"