export const industries = [
  { value: 'restaurant', label: 'Restaurant & Food Service' },
  { value: 'healthcare', label: 'Healthcare & Medical' },
  { value: 'legal', label: 'Legal Services' },
  { value: 'real-estate', label: 'Real Estate' },
  { value: 'construction', label: 'Construction & Contracting' },
  { value: 'automotive', label: 'Automotive Services' },
  { value: 'beauty', label: 'Beauty & Wellness' },
  { value: 'fitness', label: 'Fitness & Gym' },
  { value: 'education', label: 'Education & Training' },
  { value: 'technology', label: 'Technology & Software' },
  { value: 'finance', label: 'Financial Services' },
  { value: 'retail', label: 'Retail & E-commerce' },
  { value: 'consulting', label: 'Consulting & Professional Services' },
  { value: 'marketing', label: 'Marketing & Advertising' },
  { value: 'nonprofit', label: 'Non-Profit Organization' },
  { value: 'other', label: 'Other' }
];

export const servicesByIndustry: Record<string, string[]> = {
  restaurant: [
    'Dine-in Service',
    'Takeout & Delivery',
    'Catering',
    'Private Events',
    'Bar Service',
    'Online Ordering',
    'Meal Prep',
    'Food Truck'
  ],
  healthcare: [
    'Primary Care',
    'Urgent Care',
    'Specialty Care',
    'Telemedicine',
    'Diagnostic Services',
    'Physical Therapy',
    'Mental Health Services',
    'Dental Care',
    'Vision Care',
    'Pharmacy Services'
  ],
  legal: [
    'Personal Injury',
    'Family Law',
    'Criminal Defense',
    'Corporate Law',
    'Real Estate Law',
    'Immigration Law',
    'Bankruptcy',
    'Estate Planning',
    'Intellectual Property',
    'Employment Law'
  ],
  'real-estate': [
    'Residential Sales',
    'Commercial Sales',
    'Property Management',
    'Real Estate Investment',
    'Home Staging',
    'Property Valuation',
    'Rental Services',
    'Real Estate Consulting'
  ],
  construction: [
    'General Contracting',
    'Home Renovation',
    'Commercial Construction',
    'Roofing',
    'Plumbing',
    'Electrical Work',
    'HVAC Services',
    'Landscaping',
    'Painting',
    'Flooring'
  ],
  automotive: [
    'Auto Repair',
    'Oil Changes',
    'Tire Services',
    'Body Work',
    'Detailing',
    'Diagnostics',
    'Transmission Repair',
    'Brake Service',
    'AC Service',
    'Custom Modifications'
  ],
  beauty: [
    'Hair Styling',
    'Hair Coloring',
    'Nail Services',
    'Facial Treatments',
    'Massage Therapy',
    'Waxing',
    'Makeup Services',
    'Eyebrow & Lash Services',
    'Skin Care',
    'Body Treatments'
  ],
  fitness: [
    'Personal Training',
    'Group Classes',
    'Yoga',
    'Pilates',
    'CrossFit',
    'Spin Classes',
    'Martial Arts',
    'Swimming',
    'Nutrition Coaching',
    'Online Training'
  ],
  education: [
    'Tutoring',
    'Test Preparation',
    'Language Training',
    'Professional Development',
    'Online Courses',
    'Workshops',
    'Certification Programs',
    'Career Counseling'
  ],
  technology: [
    'Web Development',
    'Mobile App Development',
    'Software Development',
    'IT Support',
    'Cloud Services',
    'Cybersecurity',
    'Data Analytics',
    'AI/ML Solutions',
    'System Integration',
    'Digital Transformation'
  ],
  finance: [
    'Financial Planning',
    'Investment Management',
    'Tax Preparation',
    'Accounting',
    'Bookkeeping',
    'Insurance Services',
    'Mortgage Services',
    'Retirement Planning',
    'Business Consulting',
    'Wealth Management'
  ],
  retail: [
    'In-Store Shopping',
    'Online Sales',
    'Curbside Pickup',
    'Home Delivery',
    'Personal Shopping',
    'Custom Orders',
    'Gift Wrapping',
    'Loyalty Programs',
    'Product Customization'
  ],
  consulting: [
    'Business Strategy',
    'Management Consulting',
    'HR Consulting',
    'IT Consulting',
    'Marketing Strategy',
    'Operations Improvement',
    'Change Management',
    'Risk Management',
    'Project Management'
  ],
  marketing: [
    'Digital Marketing',
    'Social Media Management',
    'SEO Services',
    'Content Creation',
    'PPC Advertising',
    'Email Marketing',
    'Brand Strategy',
    'Video Production',
    'Graphic Design',
    'Web Design'
  ],
  nonprofit: [
    'Fundraising',
    'Community Outreach',
    'Volunteer Coordination',
    'Grant Writing',
    'Program Development',
    'Event Planning',
    'Advocacy',
    'Education Programs',
    'Support Services'
  ],
  other: [
    'Custom Service 1',
    'Custom Service 2',
    'Custom Service 3',
    'Custom Service 4',
    'Custom Service 5',
    'Custom Service 6'
  ]
};

export const states = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' }
];